# https://github.com/marketplace/actions/github-actions-version-updater

name: Update GitHub Actions

"on":
  workflow_dispatch:
  schedule:
    # First day of each month at noon
    - cron: "0 12 1 * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          token: ${{ secrets.ACTIONS_VERSION_UPDATER_TOKEN }}
      - uses: saadmk11/github-actions-version-updater@5d7d1286cb239c77a611861d710cfffaeea05fd2
        with:
          token: ${{ secrets.ACTIONS_VERSION_UPDATER_TOKEN }}
          update_version_with: release-commit-sha

permissions:
  contents: read
  pull-requests: write
